### ISSUE TITLE
mingw64

### ISSUE THREAD

**Issue by user706** [Microsoft/CmakeSettings#1]
Hi,

regarding  [CmakeSettings/mingw64/CMakeSettings.json](https://github.com/Microsoft/CmakeSettings/blob/42a0acabae2f5fd466ade8d793c5ec7764ff30a8/mingw64/CMakeSettings.json).

That is exactly hardcoded into Visual Studio if I have a project without `CMakeSettings.json` and then choose  
"Change CMake Settings"-> **Mingw64-Debug**

![Change CMake Settings](https://msdnshared.blob.core.windows.net/media/2018/06/Configuration-Template-Selector.png)

it creates a CMakeSettings.json 

Problem is:  
that CMakeSettings.json has
`"TOOLSET_VERSION"` hardcoded to `"7.3.0"` and then used in [line 12](https://github.com/Microsoft/CmakeSettings/blob/42a0acabae2f5fd466ade8d793c5ec7764ff30a8/mingw64/CMakeSettings.json#L12)

```
"INCLUDE": \
"${env.INCLUDE};\
${env.MINGW64_ROOT}\\include\\c++\\${env.TOOLSET_VERSION};\
${env.MINGW64_ROOT}\\include\\c++\\${env.TOOLSET_VERSION}\\tr1;\
${env.MINGW64_ROOT}\\include\\c++\\${env.TOOLSET_VERSION}\\${env.FLAVOR}"

// corresponding to 
//C:\msys64\mingw64\include\c++\7.3.0
//C:\msys64\mingw64\include\c++\7.3.0\tr1
//C:\msys64\mingw64\include\c++\7.3.0\x86_64-w64-mingw32
```

Well I regularly update msys2 with command `pacman -Syuu`, and currently `TOOLSET_VERSION` of mingw64 is no longer 7.3.0, but instead **8.2.1**:
```
C:\msys64\mingw64\include\c++\8.2.1
C:\msys64\mingw64\include\c++\8.2.1\tr1
C:\msys64\mingw64\include\c++\8.2.1\x86_64-w64-mingw32
```

Thus questions: is there any way that Visual Studio can autodetect this? (I guess the only way is for me to set an environment variable (globally, outside of Visual Studio), and then reference it) 

Oh and what does that [INCLUDE](https://github.com/Microsoft/CmakeSettings/blob/42a0acabae2f5fd466ade8d793c5ec7764ff30a8/mingw64/CMakeSettings.json#L12) environment variable do anyway? Is it necessary at all?

Thanks.

**Comment by rchiodo** [comment]
VS doesn't detect mingw versions at the moment so yes, you'd have to set an environment variable somewhere else. 

The Include variable is used by CMake to generate include paths in the generated projects.

@WillBuik can help you out if you need anymore information.
